import { Platform } from 'react-native';

/**
 * User model representing a user entity.
 */
export interface User {
  /** Unique identifier */
  id: string;
  /** Full name */
  name: string;
  /** Email address */
  email: string;
  /** Optional avatar image URL */
  avatarUrl?: string;
  /** Creation timestamp */
  createdAt: Date;
  /** Optional last update timestamp */
  updatedAt?: Date;
}

/**
 * Input shape used when creating or updating a user.
 * `id`, `createdAt` and timestamps are optional because they can be generated by the backend.
 */
export type UserInput = Partial<Omit<User, 'createdAt' | 'updatedAt'>> & {
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

/**
 * Default empty user used as a fallback.
 */
export const DEFAULT_USER: User = {
  id: '',
  name: '',
  email: '',
  createdAt: new Date(),
};

/**
 * Runtime validation for a raw object that should represent a User.
 * Throws an error if validation fails.
 */
export const assertValidUserData = (data: unknown): asserts data is Record<string, any> => {
  if (typeof data !== 'object' || data === null) {
    throw new Error('User data must be a non‑null object');
  }
  const record = data as Record<string, any>;

  if (typeof record.id !== 'string' && typeof record.id !== 'number') {
    throw new Error('User.id must be a string or number');
  }
  if (typeof record.name !== 'string') {
    throw new Error('User.name must be a string');
  }
  if (typeof record.email !== 'string') {
    throw new Error('User.email must be a string');
  }
  if (record.avatarUrl !== undefined && typeof record.avatarUrl !== 'string') {
    throw new Error('User.avatarUrl must be a string if provided');
  }
  if (record.createdAt !== undefined && isNaN(Date.parse(record.createdAt))) {
    throw new Error('User.createdAt must be a valid date string');
  }
  if (record.updatedAt !== undefined && isNaN(Date.parse(record.updatedAt))) {
    throw new Error('User.updatedAt must be a valid date string');
  }
};

/**
 * Parses a raw JSON value into a strongly typed {@link User}.
 * Performs runtime validation and normalises date fields.
 *
 * @param json Raw JSON received from an API or storage.
 * @returns A {@link User} instance.
 */
export const parseUser = (json: unknown): User => {
  assertValidUserData(json);
  const data = json as Record<string, any>;

  const createdAt = data.createdAt ? new Date(data.createdAt) : new Date();
  const updatedAt = data.updatedAt ? new Date(data.updatedAt) : undefined;

  return {
    id: String(data.id ?? ''),
    name: String(data.name ?? ''),
    email: String(data.email ?? ''),
    avatarUrl: data.avatarUrl ?? undefined,
    createdAt,
    updatedAt,
  };
};

/**
 * Serialises a {@link User} into a plain object suitable for JSON.stringify or API payloads.
 *
 * @param user The user to serialise.
 * @returns Plain object representation.
 */
export const userToJson = (user: User): Record<string, any> => ({
  id: user.id,
  name: user.name,
  email: user.email,
  avatarUrl: user.avatarUrl,
  createdAt: user.createdAt.toISOString(),
  updatedAt: user.updatedAt?.toISOString(),
});

/**
 * Creates a new {@link User} from partial input, merging with defaults.
 *
 * @param input Partial user data, typically from a form or API response.
 * @returns Fully populated {@link User}.
 */
export const createUser = (input: UserInput): User => {
  const now = new Date();

  return {
    id: input.id ? String(input.id) : '',
    name: input.name ?? '',
    email: input.email ?? '',
    avatarUrl: input.avatarUrl,
    createdAt:
      input.createdAt instanceof Date
        ? input.createdAt
        : input.createdAt
        ? new Date(input.createdAt)
        : now,
    updatedAt:
      input.updatedAt instanceof Date
        ? input.updatedAt
        : input.updatedAt
        ? new Date(input.updatedAt)
        : undefined,
  };
};

/**
 * Returns a shallow copy of a {@link User} with the supplied updates applied.
 *
 * @param user Original user object.
 * @param updates Partial fields to override.
 * @returns Updated user instance.
 */
export const copyUser = (user: User, updates: Partial<User>): User => ({
  ...user,
  ...updates,
  createdAt: updates.createdAt ?? user.createdAt,
  updatedAt: updates.updatedAt ?? user.updatedAt,
});

/**
 * Platform‑specific helper to format the avatar URL.
 * On Android we might need to prepend a file scheme for local assets.
 *
 * @param url Original avatar URL.
 * @returns Platform‑adjusted URL.
 */
export const getPlatformAvatarUrl = (url?: string): string | undefined => {
  if (!url) return undefined;
  if (Platform.OS === 'android' && url.startsWith('file://')) {
    // Android requires absolute file paths without the scheme for some libraries.
    return url.replace('file://', '');
  }
  return url;
};